<?php

namespace Omnipay\FirstData\Model\RapidConnect\Common;

class POSConditionCode
{
    const CARDHOLDER_PRESENT_CARD_PRESENT = '00';
    const CARDHOLDER_PRESENT_UNSPECIFIED = '01';
    const CARDHOLDER_PRESENT_UNATTENDED_DEVICE = '02';
    const CARDHOLDER_PRESENT_SUSPECT_FRAUD = '03';
    const CARDHOLDER_NOT_PRESENT_RECURRING = '04';
    const CARDHOLDER_PRESENT_CARD_NOT_PRESENT = '05';
    const CARDHOLDER_PRESENT_IDENTITY_VERIFIED = '06';
    const CARDHOLDER_NOT_PRESENT_MAIL_TELEPHONE = '08';
    const CARDHOLDER_NOT_PRESENT_ECOMMERCE = '59';
    const CARDHOLDER_PRESENT_MAGNETIC_STRIPE_NOT_READ = '71';
}